#!/usr/bin/env bash

#This is an array in which you populate the URL's of the Websites you want to
#capture

websites=("https://nyctmc.org/google_popup.php?cid=483"
"https://nyctmc.org/google_popup.php?cid=543")

for site in ${websites[@]};

do
	echo "analyzing $site"
	python WebsiteVidCapture.py "$site" &
done
